# Generated by Django 3.0.3 on 2020-02-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0002_invitation_when_to_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(help_text="It's always nice to add a friendly message!", max_length=300, verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select the user you want to play a game with', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='when_to_play',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Recommend a time to play', verbose_name='I can play at:'),
        ),
    ]
